name: Deploy docs
on: [push]
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install Python libs
        run: pip install --no-deps -r docs/requirements.txt
      - name: Install Crystal libs
        run: shards install
      - name: Copy README
        run: cp ./README.md ./docs/README.md
      - name: Build site
        run: mkdocs build
      # - name: Fix CNAME
      #   run: echo docs.celestine.dev > docs/CNAME
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: mkdocs gh-deploy --force
